title: "Homely Vibes"
description: "🏠 Smart IoT Home Automation & Monitoring System with ML-powered Analytics"
url: "https://homely-vibes.deviationlabs.com"
baseurl: ""

# GitHub integration - ensure assets load from GitHub Pages
github:
  repository_url: "https://github.com/abutala/homely-vibes"
  repository_name: "homely-vibes"
  owner_name: "abutala"
  owner_url: "https://github.com/abutala"
  is_project_page: true

# SEO and social
author: "Amit Butala"
twitter:
  username: abutala
social:
  name: "Amit Butala"
  links:
    - "https://github.com/abutala"

# Page metadata
lang: en
timezone: America/Los_Angeles

plugins:
- jekyll-readme-index

# Enable HTML in markdown for better styling
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Exclude directories that contain application code, not website content
exclude:
- WaterParser/
- Tesla/
- RachioFlume/
- Bimpop.ai/
- BrowserAlert/
- GarageCheck/
- LambdaEmailFwder/
- NetworkCheck/
- NodeCheck/
- OpenAIAdmin/
- WaterLogging/
- lib/
- scripts/
- backups/
- uv.lock
- pyproject.toml
- Makefile
- .python-version
