title: "Homely Vibes"
description: "IoT Home Automation and Monitoring System"
url: "https://homely-vibes.deviationlabs.com"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-readme-index

# Exclude directories that contain application code, not website content
exclude:
- WaterParser/
- Tesla/
- RachioFlume/
- Bimpop.ai/
- BrowserAlert/
- GarageCheck/
- LambdaEmailFwder/
- NetworkCheck/
- NodeCheck/
- OpenAIAdmin/
- WaterLogging/
- lib/
- scripts/
- backups/
- uv.lock
- pyproject.toml
- Makefile
- .python-version
